/*
Apex Private API

Private (authenticated) API to integrate with your local Apex aquarium controller (AOS 5 compatible).

API version: 1.0.0-alpha.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
)

// GetStatusResponse struct for GetStatusResponse
type GetStatusResponse struct {
	System  SystemStatus             `json:"system"`
	Modules []map[string]interface{} `json:"modules"`
	Nstat   map[string]interface{}   `json:"nstat"`
	Feed    map[string]interface{}   `json:"feed"`
	Power   map[string]interface{}   `json:"power"`
	Outputs []map[string]interface{} `json:"outputs"`
	Inputs  []map[string]interface{} `json:"inputs"`
	Link    map[string]interface{}   `json:"link"`
}

// NewGetStatusResponse instantiates a new GetStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatusResponse(system SystemStatus, modules []map[string]interface{}, nstat map[string]interface{}, feed map[string]interface{}, power map[string]interface{}, outputs []map[string]interface{}, inputs []map[string]interface{}, link map[string]interface{}) *GetStatusResponse {
	this := GetStatusResponse{}
	this.System = system
	this.Modules = modules
	this.Nstat = nstat
	this.Feed = feed
	this.Power = power
	this.Outputs = outputs
	this.Inputs = inputs
	this.Link = link
	return &this
}

// NewGetStatusResponseWithDefaults instantiates a new GetStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatusResponseWithDefaults() *GetStatusResponse {
	this := GetStatusResponse{}
	return &this
}

// GetSystem returns the System field value
func (o *GetStatusResponse) GetSystem() SystemStatus {
	if o == nil {
		var ret SystemStatus
		return ret
	}

	return o.System
}

// GetSystemOk returns a tuple with the System field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetSystemOk() (*SystemStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.System, true
}

// SetSystem sets field value
func (o *GetStatusResponse) SetSystem(v SystemStatus) {
	o.System = v
}

// GetModules returns the Modules field value
func (o *GetStatusResponse) GetModules() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Modules
}

// GetModulesOk returns a tuple with the Modules field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetModulesOk() (*[]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modules, true
}

// SetModules sets field value
func (o *GetStatusResponse) SetModules(v []map[string]interface{}) {
	o.Modules = v
}

// GetNstat returns the Nstat field value
func (o *GetStatusResponse) GetNstat() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Nstat
}

// GetNstatOk returns a tuple with the Nstat field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetNstatOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nstat, true
}

// SetNstat sets field value
func (o *GetStatusResponse) SetNstat(v map[string]interface{}) {
	o.Nstat = v
}

// GetFeed returns the Feed field value
func (o *GetStatusResponse) GetFeed() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Feed
}

// GetFeedOk returns a tuple with the Feed field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetFeedOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Feed, true
}

// SetFeed sets field value
func (o *GetStatusResponse) SetFeed(v map[string]interface{}) {
	o.Feed = v
}

// GetPower returns the Power field value
func (o *GetStatusResponse) GetPower() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Power
}

// GetPowerOk returns a tuple with the Power field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetPowerOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Power, true
}

// SetPower sets field value
func (o *GetStatusResponse) SetPower(v map[string]interface{}) {
	o.Power = v
}

// GetOutputs returns the Outputs field value
func (o *GetStatusResponse) GetOutputs() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetOutputsOk() (*[]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outputs, true
}

// SetOutputs sets field value
func (o *GetStatusResponse) SetOutputs(v []map[string]interface{}) {
	o.Outputs = v
}

// GetInputs returns the Inputs field value
func (o *GetStatusResponse) GetInputs() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetInputsOk() (*[]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inputs, true
}

// SetInputs sets field value
func (o *GetStatusResponse) SetInputs(v []map[string]interface{}) {
	o.Inputs = v
}

// GetLink returns the Link field value
func (o *GetStatusResponse) GetLink() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *GetStatusResponse) GetLinkOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *GetStatusResponse) SetLink(v map[string]interface{}) {
	o.Link = v
}

func (o GetStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["system"] = o.System
	}
	if true {
		toSerialize["modules"] = o.Modules
	}
	if true {
		toSerialize["nstat"] = o.Nstat
	}
	if true {
		toSerialize["feed"] = o.Feed
	}
	if true {
		toSerialize["power"] = o.Power
	}
	if true {
		toSerialize["outputs"] = o.Outputs
	}
	if true {
		toSerialize["inputs"] = o.Inputs
	}
	if true {
		toSerialize["link"] = o.Link
	}
	return json.Marshal(toSerialize)
}

type NullableGetStatusResponse struct {
	value *GetStatusResponse
	isSet bool
}

func (v NullableGetStatusResponse) Get() *GetStatusResponse {
	return v.value
}

func (v *NullableGetStatusResponse) Set(val *GetStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatusResponse(val *GetStatusResponse) *NullableGetStatusResponse {
	return &NullableGetStatusResponse{value: val, isSet: true}
}

func (v NullableGetStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
