/*
Apex Private API

Private (authenticated) API to integrate with your local Apex aquarium controller (AOS 5 compatible).

API version: 1.0.0-alpha.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
)

// ModuleConfig struct for ModuleConfig
type ModuleConfig struct {
	Abaddr     float32                           `json:"abaddr"`
	Name       string                            `json:"name"`
	Hwtype     string                            `json:"hwtype"`
	Update     bool                              `json:"update"`
	UpdateStat float32                           `json:"updateStat"`
	Extra      map[string]map[string]interface{} `json:"extra"`
}

// NewModuleConfig instantiates a new ModuleConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModuleConfig(abaddr float32, name string, hwtype string, update bool, updateStat float32, extra map[string]map[string]interface{}) *ModuleConfig {
	this := ModuleConfig{}
	this.Abaddr = abaddr
	this.Name = name
	this.Hwtype = hwtype
	this.Update = update
	this.UpdateStat = updateStat
	this.Extra = extra
	return &this
}

// NewModuleConfigWithDefaults instantiates a new ModuleConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModuleConfigWithDefaults() *ModuleConfig {
	this := ModuleConfig{}
	return &this
}

// GetAbaddr returns the Abaddr field value
func (o *ModuleConfig) GetAbaddr() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Abaddr
}

// GetAbaddrOk returns a tuple with the Abaddr field value
// and a boolean to check if the value has been set.
func (o *ModuleConfig) GetAbaddrOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Abaddr, true
}

// SetAbaddr sets field value
func (o *ModuleConfig) SetAbaddr(v float32) {
	o.Abaddr = v
}

// GetName returns the Name field value
func (o *ModuleConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ModuleConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ModuleConfig) SetName(v string) {
	o.Name = v
}

// GetHwtype returns the Hwtype field value
func (o *ModuleConfig) GetHwtype() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hwtype
}

// GetHwtypeOk returns a tuple with the Hwtype field value
// and a boolean to check if the value has been set.
func (o *ModuleConfig) GetHwtypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hwtype, true
}

// SetHwtype sets field value
func (o *ModuleConfig) SetHwtype(v string) {
	o.Hwtype = v
}

// GetUpdate returns the Update field value
func (o *ModuleConfig) GetUpdate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Update
}

// GetUpdateOk returns a tuple with the Update field value
// and a boolean to check if the value has been set.
func (o *ModuleConfig) GetUpdateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Update, true
}

// SetUpdate sets field value
func (o *ModuleConfig) SetUpdate(v bool) {
	o.Update = v
}

// GetUpdateStat returns the UpdateStat field value
func (o *ModuleConfig) GetUpdateStat() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UpdateStat
}

// GetUpdateStatOk returns a tuple with the UpdateStat field value
// and a boolean to check if the value has been set.
func (o *ModuleConfig) GetUpdateStatOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateStat, true
}

// SetUpdateStat sets field value
func (o *ModuleConfig) SetUpdateStat(v float32) {
	o.UpdateStat = v
}

// GetExtra returns the Extra field value
func (o *ModuleConfig) GetExtra() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Extra
}

// GetExtraOk returns a tuple with the Extra field value
// and a boolean to check if the value has been set.
func (o *ModuleConfig) GetExtraOk() (*map[string]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Extra, true
}

// SetExtra sets field value
func (o *ModuleConfig) SetExtra(v map[string]map[string]interface{}) {
	o.Extra = v
}

func (o ModuleConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["abaddr"] = o.Abaddr
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["hwtype"] = o.Hwtype
	}
	if true {
		toSerialize["update"] = o.Update
	}
	if true {
		toSerialize["updateStat"] = o.UpdateStat
	}
	if true {
		toSerialize["extra"] = o.Extra
	}
	return json.Marshal(toSerialize)
}

type NullableModuleConfig struct {
	value *ModuleConfig
	isSet bool
}

func (v NullableModuleConfig) Get() *ModuleConfig {
	return v.value
}

func (v *NullableModuleConfig) Set(val *ModuleConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableModuleConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableModuleConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModuleConfig(val *ModuleConfig) *NullableModuleConfig {
	return &NullableModuleConfig{value: val, isSet: true}
}

func (v NullableModuleConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModuleConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
