/*
Apex Public API

Public (unauthenticated) API to integrate with your local Apex aquarium controller (AOS 5 compatible).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// StatusLink struct for StatusLink
type StatusLink struct {
	LinkState int32  `json:"linkState"`
	LinkKey   string `json:"linkKey"`
	Link      bool   `json:"link"`
}

// NewStatusLink instantiates a new StatusLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusLink(linkState int32, linkKey string, link bool) *StatusLink {
	this := StatusLink{}
	this.LinkState = linkState
	this.LinkKey = linkKey
	this.Link = link
	return &this
}

// NewStatusLinkWithDefaults instantiates a new StatusLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusLinkWithDefaults() *StatusLink {
	this := StatusLink{}
	return &this
}

// GetLinkState returns the LinkState field value
func (o *StatusLink) GetLinkState() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LinkState
}

// GetLinkStateOk returns a tuple with the LinkState field value
// and a boolean to check if the value has been set.
func (o *StatusLink) GetLinkStateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkState, true
}

// SetLinkState sets field value
func (o *StatusLink) SetLinkState(v int32) {
	o.LinkState = v
}

// GetLinkKey returns the LinkKey field value
func (o *StatusLink) GetLinkKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LinkKey
}

// GetLinkKeyOk returns a tuple with the LinkKey field value
// and a boolean to check if the value has been set.
func (o *StatusLink) GetLinkKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkKey, true
}

// SetLinkKey sets field value
func (o *StatusLink) SetLinkKey(v string) {
	o.LinkKey = v
}

// GetLink returns the Link field value
func (o *StatusLink) GetLink() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *StatusLink) GetLinkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *StatusLink) SetLink(v bool) {
	o.Link = v
}

func (o StatusLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["linkState"] = o.LinkState
	}
	if true {
		toSerialize["linkKey"] = o.LinkKey
	}
	if true {
		toSerialize["link"] = o.Link
	}
	return json.Marshal(toSerialize)
}

type NullableStatusLink struct {
	value *StatusLink
	isSet bool
}

func (v NullableStatusLink) Get() *StatusLink {
	return v.value
}

func (v *NullableStatusLink) Set(val *StatusLink) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusLink) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusLink(val *StatusLink) *NullableStatusLink {
	return &NullableStatusLink{value: val, isSet: true}
}

func (v NullableStatusLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
