/*
Apex Public API

Public (unauthenticated) API to integrate with your local Apex aquarium controller (AOS 5 compatible).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// DatalogData struct for DatalogData
type DatalogData struct {
	// name
	Name string `json:"name"`
	// did
	Did string `json:"did"`
	// type
	Type string `json:"type"`
	// value
	Value string `json:"value"`
}

// NewDatalogData instantiates a new DatalogData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatalogData(name string, did string, type_ string, value string) *DatalogData {
	this := DatalogData{}
	this.Name = name
	this.Did = did
	this.Type = type_
	this.Value = value
	return &this
}

// NewDatalogDataWithDefaults instantiates a new DatalogData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatalogDataWithDefaults() *DatalogData {
	this := DatalogData{}
	return &this
}

// GetName returns the Name field value
func (o *DatalogData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DatalogData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DatalogData) SetName(v string) {
	o.Name = v
}

// GetDid returns the Did field value
func (o *DatalogData) GetDid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Did
}

// GetDidOk returns a tuple with the Did field value
// and a boolean to check if the value has been set.
func (o *DatalogData) GetDidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Did, true
}

// SetDid sets field value
func (o *DatalogData) SetDid(v string) {
	o.Did = v
}

// GetType returns the Type field value
func (o *DatalogData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DatalogData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DatalogData) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *DatalogData) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *DatalogData) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *DatalogData) SetValue(v string) {
	o.Value = v
}

func (o DatalogData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["did"] = o.Did
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableDatalogData struct {
	value *DatalogData
	isSet bool
}

func (v NullableDatalogData) Get() *DatalogData {
	return v.value
}

func (v *NullableDatalogData) Set(val *DatalogData) {
	v.value = val
	v.isSet = true
}

func (v NullableDatalogData) IsSet() bool {
	return v.isSet
}

func (v *NullableDatalogData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatalogData(val *DatalogData) *NullableDatalogData {
	return &NullableDatalogData{value: val, isSet: true}
}

func (v NullableDatalogData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatalogData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
